name: downsta
description: An app to download posts, stories, reels and videos from instagram.

publish_to: 'none'

version: 1.0.1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  path_provider: ^2.0.11
  cookie_jar: ^4.0.5
  http: ^0.13.4
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.0
  photo_view: ^0.14.0
  smooth_page_indicator: ^1.0.0+2
  video_player: ^2.4.5
  chewie: ^1.3.4
  drift: ^2.9.0
  drift_dev: ^2.9.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.3
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/
